In [1]:
import sys
from importlib import reload

In [2]:
    from utils_fcard_widget import Flashcards

In [3]:
reload(sys.modules['utils_fcard_widget'])
from utils_fcard_widget import Flashcards

In [4]:
# Expand the maximum allowed column width.
import pandas as pd
pd.set_option('display.max_colwidth', 5000)

# Latest deck

In [5]:
ls_output = !ls deck
fname_latest = "deck/" + list(filter(lambda x: x.startswith('deck'), ls_output))[-1] # latest saved down
print(fname_latest)

deck/deck_20220528_2220

# Display

In [6]:
fc = Flashcards(fname=fname_latest)

HBox(children=(VBox(children=(HTML(value="<p style='font-size:large'>Edit deck</p>"), HBox(children=(VBox(chil…

# Save

In [13]:
fc.pickle_me()

# Learn

In [11]:
fc.shuffle(source='Augen auf China 1-19', damp=2)

HBox(children=(VBox(children=(HTML(value="<p style='font-size:xx-large'>毁坏</p>", layout=Layout(margin='2px 10p…

In [12]:
fc.batch(batch_size=10, source='eine Reise nach China 21-36')

HBox(children=(VBox(children=(HTML(value="<p style='font-size:xx-large'>灌溉</p>", layout=Layout(margin='2px 10p…

In [13]:
fc.show_progress()

# Examine deck

In [14]:
fc.show()

,char,pinyin,eng,source,score
0,贵姓,guì xìng,surname,der erste Schritt,2
1,支,zhī,measure word for stick-like things,der erste Schritt,1
2,旁,páng,side,der erste Schritt,1
3,汉堡包,hàn bǎo bāo,hamburger,der erste Schritt,1
4,墨,mò,ink,der erste Schritt,2
...,...,...,...,...,...
2863,煽,shān,"to fan into a flame, incite",Augen auf China 20-30,0
2864,曝光,bào guāng,"to expose (photography, scandal)",Augen auf China 20-30,1
2865,对比,duì bǐ,"to contrast, compare",Augen auf China 20-30,1
2866,纷纷,fēn fēn,"one after another, numerous in succession",Augen auf China 20-30,2
2867,案例,àn lì,case,Augen auf China 20-30,2

In [15]:
fc.get_char('恶劣')

     char pinyin            eng                source score
2546   恶劣  è liè  hostile, vile  Augen auf China 1-19     1

In [16]:
fc.get_eng('open')

,char,pinyin,eng,source,score
625,通,tōng,"through, open, common",oh China 18-26,1
988,开明,kāi míng,"enlightened, open-minded",oh China 27-35,1
1121,虚心,xū xīn,"open-minded, modest",oh China 27-35,2
1442,拆,chāi,"to tear down, open",eine Reise nach China 21-36,0
2080,开通,kāi tong,"open-minded, liberal",alles in allem 1-20,1
2476,明目张胆,míng mù zhāng dǎn,"to do bad openly and unscrupulously, flagrantly",alles in allem 21-32,1
2506,开幕,kāi mù,"to open (a conference), inaugurate",alles in allem 21-32,1
2567,四通八达,sì tōng bā dá,roads open in all directions (idiom),Augen auf China 1-19,2
2667,爽朗,shuǎng lǎng,"clear and bright (weather), candid and open (person)",Augen auf China 1-19,1

In [17]:
fc.get_source('eine Reise nach China 21-36').sort_values(by='score', kind='mergesort').head(20)

,char,pinyin,eng,source,score
1541,屠杀,tú shā,to massacre,eine Reise nach China 21-36,-2
1327,示威,shì wēi,to demonstrate (as a protest),eine Reise nach China 21-36,-1
1389,信仰,xìn yǎng,"faith, religious belief",eine Reise nach China 21-36,-1
1404,芭蕾,bā léi,ballet,eine Reise nach China 21-36,-1
1454,灌溉,guàn gài,"to irrigate, irrigation",eine Reise nach China 21-36,-1
1460,原始,yuán shǐ,"primitive, original",eine Reise nach China 21-36,-1
1502,唐朝,táng cháo,Tang Dynasty,eine Reise nach China 21-36,-1
1521,贪污,tān wū,"to embezzle, corruption",eine Reise nach China 21-36,-1
1577,诚心,chéng xīn,wholeheartedly,eine Reise nach China 21-36,-1
1311,戒烟,jiè yān,to quit smoking,eine Reise nach China 21-36,0
1312,干嘛,gàn má,why,eine Reise nach China 21-36,0
1313,肺癌,fèi ái,lung cancer,eine Reise nach China 21-36,0
1320,决,jué,to decide,eine Reise nach China 21-36,0
1321,转播,zhuǎn bō,"to relay, broadcast (on radio or TV)",eine Reise nach China 21-36,0
1324,耽误,dān wù,"to delay, waste time",eine Reise nach China 21-36,0
1325,欺负,qī fù,to bully,eine Reise nach China 21-36,0
1329,喊,hǎn,to shout,eine Reise nach China 21-36,0
1331,侮,wǔ,to insult,eine Reise nach China 21-36,0
1333,侮辱,wǔ rǔ,to insult,eine Reise nach China 21-36,0
1341,者,zhě,-ist,eine Reise nach China 21-36,0